version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: banner_rotation
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      DB_CONNSTR: "postgresql://user:password@postgres:5432/banner_rotation?sslmode=disable"
    depends_on:
      - postgres
